src/Web/Models/PageTypes/RegisterPage.cs
/*
Commerce Starter Kit for EPiServer

All rights reserved. See LICENSE.txt in project root.

Copyright (C) 2013-2014 Oxx AS
Copyright (C) 2013-2014 BV Network AS

*/

using System.ComponentModel.DataAnnotations;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPi.Commerce.Core.Attributes;

namespace EPi.Commerce.Web.Models.PageTypes
{
	[ContentType(GUID = "5dbe7b83-38e0-43f6-9663-0611829f7949",
	 DisplayName = "Register user page",
	 Description = "Settings for the register user page and welcome email",
     GroupName = WebGlobal.GroupNames.Specialized,
	 AvailableInEditMode = false, 
	 Order = 100)]
    [SiteImageUrl(thumbnail: EditorThumbnail.Social)]
	public class RegisterPage : SitePage
	{
		[Display(
			Name = "Content area top",
			GroupName = SystemTabNames.Content,
			Order = 10)]
		public virtual ContentArea PreBodyContent { get; set; }

		[Display(
			Name = "Welcome email subject",
			GroupName = SystemTabNames.Content,
			Order = 20)]
		[CultureSpecific]
		public virtual string EmailSubject { get; set; }

		[Display(
			Name = "Welcome email text",
			GroupName = SystemTabNames.Content,
			Order = 40)]
		[CultureSpecific]
		public virtual XhtmlString EmailBody { get; set; }
	}
}

src/Web/Models/ViewModels/RegisterPageViewModel.cs
/*
Commerce Starter Kit for EPiServer

All rights reserved. See LICENSE.txt in project root.

Copyright (C) 2013-2014 Oxx AS
Copyright (C) 2013-2014 BV Network AS

*/

using EPi.Commerce.Core.Objects;
using EPi.Commerce.Web.Models.PageTypes;

namespace EPi.Commerce.Web.Models.ViewModels
{
	public class RegisterPageViewModel : PageViewModel<RegisterPage>
	{
		public RegisterPageViewModel()
		{

		}

		public RegisterPageViewModel(RegisterPage currentPage)
			: base(currentPage)
		{
			if (RegisterForm == null)
			{
				RegisterForm = new RegisterForm();
			}
		}

		public RegisterForm RegisterForm { get; set; }
	}
}

src/Web/Controllers/RegisterPageController.cs
/*
Commerce Starter Kit for EPiServer

All rights reserved. See LICENSE.txt in project root.

Copyright (C) 2013-2014 Oxx AS
Copyright (C) 2013-2014 BV Network AS

*/

using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using EPiServer.Core;
using EPiServer.Editor;
using EPiServer.Framework.Localization;
using EPiServer.ServiceLocation;
using EPiServer.Web.Routing;
using Mediachase.BusinessFoundation.Data;
using Mediachase.Commerce;
using Mediachase.Commerce.Core;
using Mediachase.Commerce.Customers;
using Mediachase.Commerce.Security;
using EPi.Commerce.Core;
using EPi.Commerce.Core.Email;
using EPi.Commerce.Core.Extensions;
using EPi.Commerce.Core.Objects;
using EPi.Commerce.Core.Repositories.Interfaces;
using EPi.Commerce.Web.Models.PageTypes;
using EPi.Commerce.Web.Models.ViewModels;
using EPi.Commerce.Web.Services.Email;

namespace EPi.Commerce.Web.Controllers
{
	public class RegisterPageController : PageControllerBase<RegisterPage>
	{
		private readonly UrlResolver _urlResolver;
		private readonly LocalizationService _localizationService;
	    private readonly IEmailService _emailService;

		public RegisterPageController(UrlResolver urlResolver, LocalizationService localizationService, IEmailService emailService)
		{
			_urlResolver = urlResolver;
			_localizationService = localizationService;
		    _emailService = emailService;
		}

		public ActionResult Index(RegisterPage currentPage)
		{
			RegisterPageViewModel model = new RegisterPageViewModel(currentPage);
			model.RegisterForm.AvailableCategories = GetAvailableCategories();

			if (PageEditing.PageIsInEditMode)
			{
				return View("Edit", model);
			}

			if (Request.IsAjaxRequest())
			{
				return PartialView(model);
			}

			return View("Index", model);
		}

		private Dictionary<string, string> GetAvailableCategories()
		{
			var output = new Dictionary<string, string>();

			// get the Category type from the BusinessFoundation
			var category = DataContext.Current.GetMetaFieldType(Constants.Metadata.Customer.Category);
			if (category != null)
			{
				if (category.EnumItems != null)
				{
					foreach (var item in category.EnumItems.OrderBy(x => x.OrderId))
					{
						output.Add(item.Handle.ToString(), item.Name);
					}
				}
			}
			return output;
		}


		[HttpPost]
		public ActionResult Register(RegisterPage currentPage, RegisterPageViewModel model, RegisterForm registerForm, int[] SelectedCategories)
		{
			model.RegisterForm.AvailableCategories = GetAvailableCategories();
			model.RegisterForm.SelectedCategories = SelectedCategories;
			if (registerForm.Password != registerForm.PasswordConfirm)
			{
				ModelState.AddModelError("RegisterForm.ValidationMessage", _localizationService.GetString("/common/validation/compare_passwords"));
			}

			if (!ModelState.IsValid)
			{
				return View("Index", model);
			}

			string emailAddress = registerForm.UserName.Trim();
			string password = registerForm.Password;

			// Account
			MembershipUser user = null;
			MembershipCreateStatus createStatus;
			user = Membership.CreateUser(emailAddress, password, emailAddress, null, null, true, out createStatus);

			bool existingUserWithoutPassword = false;

			if (createStatus == MembershipCreateStatus.DuplicateUserName)
			{
				user = Membership.GetUser(emailAddress);
				var customer1 = CustomerContext.Current.GetContactForUser(user);
				if (customer1.GetHasPassword())
				{
					ModelState.AddModelError("RegisterForm.ValidationMessage", _localizationService.GetString("/common/account/register_error_unique_username"));
				}
				else
				{
					existingUserWithoutPassword = true;
				}
			}
			else if (user == null)
			{
				ModelState.AddModelError("RegisterForm.ValidationMessage", _localizationService.GetString("/common/account/register_error"));
			}

			if (!ModelState.IsValid)
			{
				return View("Index", model);
			}

			if (!existingUserWithoutPassword)
			{
				SecurityContext.Current.AssignUserToGlobalRole(user, AppRoles.EveryoneRole);
				SecurityContext.Current.AssignUserToGlobalRole(user, AppRoles.RegisteredRole);
			}
			else
			{
				// set new password
				var pass = user.ResetPassword();
				user.ChangePassword(pass, password);
			}

			var customer = CustomerContext.Current.GetContactForUser(user);
			customer.FirstName = registerForm.Address.FirstName;
			customer.LastName = registerForm.Address.LastName;
			customer.SetPhoneNumber(registerForm.Phone);
			customer.FullName = string.Format("{0} {1}", customer.FirstName, customer.LastName);
			customer.SetHasPassword(true);

			// member club
			if (registerForm.MemberClub)
			{
				customer.CustomerGroup = Constants.CustomerGroup.CustomerClub;
			}

			// categories
			customer.SetCategories(SelectedCategories);

			customer.SaveChanges();

			var CustomerAddressRepository = ServiceLocator.Current.GetInstance<ICustomerAddressRepository>();
			CustomerAddressRepository.SetCustomer(customer);

			// copy address fields to shipping address
			registerForm.Address.CheckAndSetCountryCode();

			var ShippingAddress = (Address)registerForm.Address.Clone();
			ShippingAddress.IsPreferredShippingAddress = true;
			CustomerAddressRepository.Save(ShippingAddress);

			registerForm.Address.IsPreferredBillingAddress = true;
			CustomerAddressRepository.Save(registerForm.Address);

			LoginController.CreateAuthenticationCookie(ControllerContext.HttpContext, emailAddress, AppContext.Current.ApplicationName, false);

			bool mail_sent = SendWelcomeEmail(registerForm.UserName, currentPage);

			return Redirect(_urlResolver.GetUrl(ContentReference.StartPage));
		}


		public bool SendWelcomeEmail(string email, RegisterPage currentPage = null)
		{
		    return _emailService.SendWelcomeEmail(email);
		}
	}
}

src/Web/Views/RegisterPage/EditorTemplates/RegisterForm.cshtml
@using EPi.Commerce.Web.Extensions
@using EPi.Commerce.Web.Helpers
@model EPi.Commerce.Core.Objects.RegisterForm

<div id="registration">

	<h2>@Html.Translate("/common/account/registerheader")</h2>

	@using (Html.BeginForm("Register", "RegisterPage", ViewContext.GetCombinedRouteValues(new { }), FormMethod.Post, UrlHelpers.AnonymousObjectToHtmlAttributes(new { id = "loginForm" })))
	{
		<div class="form-group">
			@Html.LabelFor(m => m.UserName)
			@Html.TextBoxFor(m => m.UserName, new { placeholder = @Html.Translate("/common/account/username_placeholder"), autocomplete = "off", @class = "form-control" })
			@Html.ValidationMessageFor(m => m.UserName, string.Format(Html.Translate("/common/validation/required"), Html.Translate("/common/account/username").Replace(":", "")))
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Password)
			@Html.PasswordFor(m => m.Password, new { placeholder = @Html.Translate("/common/account/password_placeholder"), @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Password, string.Format(Html.Translate("/common/validation/required"), Html.Translate("/common/account/password").Replace(":", "")))
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.PasswordConfirm)
			@Html.PasswordFor(m => m.PasswordConfirm, new { placeholder = @Html.Translate("/common/account/password_repeat_placeholder"), @class = "form-control" })
			@Html.ValidationMessageFor(m => m.PasswordConfirm, string.Format(Html.Translate("/common/validation/required"), Html.Translate("/common/account/password_repeat_placeholder").Replace(":", "")))
		</div>
		<div class="address-field">
			@Html.EditorFor(m => m.Address)
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Phone)
			@Html.TextBoxFor(m => m.Phone, new { placeholder = @Html.Translate("/common/accountpages/placeholder/phone"), @class = "form-control" })
		</div>


		<div class="form-group join-member-club">
			<label>
				<span>@Html.Translate("/common/account/memberclub/join_label")</span>
				@Html.RadioButtonFor(m => m.MemberClub, true)
				@Html.Translate("/common/account/memberclub/join_club_option")
			</label>
			<label>
				@Html.RadioButtonFor(m => m.MemberClub, false)
				@Html.Translate("/common/account/memberclub/dont_join_club_option")
			</label>
		</div>

		<div class="form-group interests" @(Model.MemberClub ? "" : "style=display:none;")>
			<strong>@Html.Translate("/common/account/interests/title")</strong><br />
			@if (Model.AvailableCategories != null)
			{
				foreach (var c in Model.AvailableCategories)
				{
					<label>
						<input type="checkbox" name="SelectedCategories" value="@c.Key" @(Model.SelectedCategories != null && Model.SelectedCategories.Any(x => x.ToString() == c.Key) ? "checked=checked" : "") />
						@Html.TranslateFallback("/common/account/interests/" + c.Value.ToLower(), c.Value)
					</label><br />
				}
			}
		</div>


		<div class="form-group">
			@Html.ValidationMessageFor(m => m.ValidationMessage)
		</div>
		<div class="form-group clearfix">
			<input type="submit" class="btn btn-default" value="@Html.Translate("/common/account/register")" />
		</div>
	}
</div>